### PR TITLE
Introduce license-maven-plugin

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by tsegismont** [comment]
Pasted from IRC:
```
<ppalaga> tsegismont: I have submitted the license plugin chnages to metrics https://github.com/rhq-project/rhq-metrics/pull/128
<ppalaga> tsegismont: especially this change might be of some interest to you https://github.com/ppalaga/rhq-metrics/commit/b1fa4ca30fa964f7b622ca9f0390d1b25bb1eca0
<ppalaga> tsegismont: It is basically just putting some explicit file extension to those file names, so that the license plugin knows how to add the license header
<ppalaga> tsegismont: I hope it is acceptable how I did it.
<ppalaga> tsegismont: You may wonder why I made the empty lines ignored https://github.com/ppalaga/rhq-metrics/commit/b1fa4ca30fa964f7b622ca9f0390d1b25bb1eca0#diff-413be26e43d8c1884f0e1efc9e079b0dR56
<ppalaga> tsegismont: It is because I was lazy to create a new license header definition that would not add an empty line at the end of license header.
<ppalaga> tsegismont: Where necessary, I added the empty query explicitly in the test https://github.com/ppalaga/rhq-metrics/commit/b1fa4ca30fa964f7b622ca9f0390d1b25bb1eca0#diff-413be26e43d8c1884f0e1efc9e079b0dR48
```
I reviewed the Influx grammar tests changes, they look good to me. Actually, I find your solution with empty query hardcoded in the test class more elegant (less error-prone).

Is that all the code changes you made? Actually there are too much files to review and I'm too lazy to checkout your PR and look at 307 header changes. I'm for merging as soon as Travis is happy (the Hawkular build tools dependency is missing right now).

**Comment by ppalaga** [comment]
@tsegismont only the "License headers added or fixed" commit ba434ce is that large - that is the result of running `mvn license:format`. Indeed it probably makes little sense to review that one. But all other commits are rather small and I'll feel better if someone looks at them before merging.

> as soon as Travis is happy (the Hawkular build tools dependency is missing right now).

But Travis has JBoss Nexus configured, does it not? Let's try to rebuild.

**Comment by ppalaga** [comment]
Build tools are indeed not in https://repository.jboss.org/nexus/content/groups/public-jboss/ yet. I asked the jboss.org guys for help.

**Comment by tsegismont** [comment]
Le 21/01/2015 22:01, Peter Palaga a écrit :
> @tsegismont <https://github.com/tsegismont> only the "License headers
> added or fixed" commit ba434ce
> <https://github.com/rhq-project/rhq-metrics/commit/ba434ceda5eb19f2c290356dca694f890316b151>
> is that large - that is the result of running |mvn license:format|.
> Indeed it probably makes little sense to review that one. But all other
> commits are rather small and I'll feel better if someone looks at them
> before merging.

Just reviewed the other ones. LGTM

> But Travis has JBoss Nexus configured, does it not? Let's try to rebuild.

Yes Travis builds the project with a custom Maven settings file, where 
JBoss repos are configured.

**Comment by tsegismont** [comment]
Le 21/01/2015 22:27, Peter Palaga a écrit :
> Build tools are indeed not in
> https://repository.jboss.org/nexus/content/groups/public-jboss/ yet. I
> asked the jboss.org guys for help.

OK. Ping me when the build is green.

**Pull request closed without merging**
